from __future__ import annotations

import re
from typing import Any

TAXONOMY_VERSION = "pathin-occupations-1.2"
ALGORITHM_VERSION = "pathin-ranking-2.5"
MODEL_VERSION = "evidence-grounded-personalization-2.5"


def role(
    role_id: str,
    title: str,
    family: str,
    *,
    level: int,
    skills: list[str],
    responsibilities: list[str],
    interests: list[str],
    industries: list[str],
    education: list[str],
    projects: list[str],
    work_styles: list[str],
    adjacent: list[str],
    pit_titles: list[str] | None = None,
    description: str,
) -> dict[str, Any]:
    return {
        "id": role_id,
        "title": title,
        "family": family,
        "level": level,
        "skills": skills,
        "responsibilities": responsibilities,
        "interests": interests,
        "industries": industries,
        "education": education,
        "projects": projects,
        "workStyles": work_styles,
        "adjacentRoleIds": adjacent,
        "pitTitles": pit_titles or [],
        "description": description,
    }


OCCUPATIONAL_TAXONOMY: list[dict[str, Any]] = [
    role(
        "software-engineer",
        "Software Engineer",
        "Software Engineering",
        level=2,
        skills=["Programming", "Python", "JavaScript", "APIs", "Git", "Debugging"],
        responsibilities=[
            "Build and maintain software",
            "Debug technical problems",
            "Review code and collaborate with product teams",
        ],
        interests=["Technology", "Building products", "Problem solving"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Computer Science", "Software Engineering", "Information Technology"],
        projects=["Web application", "API", "Automation tool"],
        work_styles=["Collaborative", "Independent focus", "Structured problem solving"],
        adjacent=["quality-assurance-analyst", "devops-engineer", "data-analyst"],
        pit_titles=["Software Engineer"],
        description="Builds, tests, and maintains software systems and product features.",
    ),
    role(
        "quality-assurance-analyst",
        "Quality Assurance Analyst",
        "Software Quality",
        level=1,
        skills=["Testing", "Debugging", "Documentation", "Automation", "Attention to detail"],
        responsibilities=[
            "Design and execute software tests",
            "Document defects and reproduction steps",
            "Partner with engineers on release quality",
        ],
        interests=["Technology", "Quality", "Problem solving"],
        industries=["Technology", "Finance", "Healthcare"],
        education=["Computer Science", "Information Technology"],
        projects=["Test plan", "Automated test suite", "Release checklist"],
        work_styles=["Structured", "Detail oriented", "Collaborative"],
        adjacent=["software-engineer", "business-analyst", "project-coordinator"],
        description="Protects product quality through systematic testing and clear defect evidence.",
    ),
    role(
        "devops-engineer",
        "DevOps Engineer",
        "Cloud and Infrastructure",
        level=2,
        skills=["Cloud", "AWS", "Automation", "Linux", "CI/CD", "Reliability"],
        responsibilities=[
            "Automate software delivery",
            "Monitor systems and improve reliability",
            "Manage cloud infrastructure",
        ],
        interests=["Infrastructure", "Automation", "Systems"],
        industries=["Technology", "Finance", "Healthcare"],
        education=["Computer Science", "Information Technology", "Engineering"],
        projects=["Cloud deployment", "CI/CD pipeline", "Monitoring dashboard"],
        work_styles=["Operational", "Analytical", "On-call collaboration"],
        adjacent=["software-engineer", "cybersecurity-analyst", "data-engineer"],
        pit_titles=["DevOps Engineer"],
        description="Improves cloud infrastructure, delivery automation, and system reliability.",
    ),
    role(
        "cybersecurity-analyst",
        "Cybersecurity Analyst",
        "Security",
        level=2,
        skills=[
            "Information Security",
            "Network Security",
            "Risk analysis",
            "Incident response",
            "Documentation",
        ],
        responsibilities=[
            "Monitor and investigate security events",
            "Assess risks and controls",
            "Document incidents and remediation",
        ],
        interests=["Security", "Risk", "Technology"],
        industries=["Technology", "Finance", "Healthcare", "Government"],
        education=["Cybersecurity", "Computer Science", "Information Technology"],
        projects=["Security assessment", "Threat model", "Incident response exercise"],
        work_styles=["Investigative", "Detail oriented", "Structured"],
        adjacent=["devops-engineer", "software-engineer", "business-analyst"],
        description="Identifies technical risk and helps organizations prevent and respond to security incidents.",
    ),
    role(
        "data-scientist",
        "Data Scientist",
        "Data and AI",
        level=3,
        skills=[
            "Python",
            "Statistics",
            "Machine Learning",
            "Data Analysis",
            "Experimentation",
            "Communication",
        ],
        responsibilities=[
            "Frame analytical questions",
            "Prepare data and evaluate models",
            "Explain findings and uncertainty",
        ],
        interests=["Data", "AI", "Research", "Decision making"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Data Science", "Statistics", "Mathematics", "Computer Science"],
        projects=["Machine learning model", "Experiment analysis", "Research project"],
        work_styles=["Analytical", "Research oriented", "Cross-functional"],
        adjacent=["data-analyst", "software-engineer", "financial-analyst"],
        pit_titles=["Data Scientist"],
        description="Uses statistics, code, and domain context to answer questions and build analytical systems.",
    ),
    role(
        "data-analyst",
        "Data Analyst",
        "Data and AI",
        level=2,
        skills=["SQL", "Data Analysis", "Spreadsheets", "Visualization", "Communication"],
        responsibilities=[
            "Clean and analyze operational data",
            "Build dashboards and recurring reports",
            "Translate findings into decisions",
        ],
        interests=["Data", "Business", "Decision making"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Statistics", "Business", "Economics", "Computer Science"],
        projects=["Dashboard", "Trend analysis", "Operational report"],
        work_styles=["Analytical", "Structured", "Stakeholder facing"],
        adjacent=["data-scientist", "business-analyst", "operations-analyst"],
        description="Turns business data into clear findings, dashboards, and decision support.",
    ),
    role(
        "robotics-engineer",
        "Robotics Engineer",
        "Robotics and Autonomous Systems",
        level=2,
        skills=[
            "Robotics",
            "CAD",
            "Embedded Systems",
            "Arduino",
            "Mechanical Design",
            "Electronics",
            "Prototyping",
            "Programming",
        ],
        responsibilities=[
            "Design and prototype robotic subsystems",
            "Integrate mechanical, electrical, and software components",
            "Test hardware behavior and document design decisions",
        ],
        interests=["Robotics", "Hardware", "Engineering", "Problem solving"],
        industries=["Engineering", "Manufacturing", "Technology", "Healthcare"],
        education=[
            "Computer Engineering",
            "Mechanical Engineering",
            "Electrical Engineering",
            "Mechatronics",
        ],
        projects=["Robot prototype", "Autonomous system", "Hardware integration"],
        work_styles=["Hands-on", "Iterative", "Cross-disciplinary"],
        adjacent=[
            "embedded-systems-engineer",
            "mechanical-design-engineer",
            "hardware-test-engineer",
            "software-engineer",
        ],
        description="Builds and tests robotic systems by combining mechanical design, electronics, embedded control, and software.",
    ),
    role(
        "embedded-systems-engineer",
        "Embedded Systems Engineer",
        "Embedded and Hardware Systems",
        level=2,
        skills=[
            "Embedded Systems",
            "Microcontrollers",
            "C/C++",
            "Arduino",
            "Electronics",
            "Debugging",
            "Hardware Testing",
            "Technical Documentation",
        ],
        responsibilities=[
            "Develop firmware for hardware devices",
            "Integrate sensors, actuators, and microcontrollers",
            "Debug timing, communication, and hardware-software issues",
        ],
        interests=["Embedded systems", "Electronics", "Hardware", "Programming"],
        industries=["Engineering", "Manufacturing", "Technology", "Healthcare"],
        education=[
            "Computer Engineering",
            "Electrical Engineering",
            "Computer Science",
        ],
        projects=["Arduino control system", "Sensor prototype", "Embedded device"],
        work_styles=["Hands-on", "Analytical", "Detail oriented"],
        adjacent=[
            "robotics-engineer",
            "hardware-test-engineer",
            "software-engineer",
        ],
        description="Develops firmware and hardware interfaces for devices, robots, sensors, and other embedded products.",
    ),
    role(
        "mechanical-design-engineer",
        "Mechanical Design Engineer",
        "Mechanical Design",
        level=2,
        skills=[
            "CAD",
            "Mechanical Design",
            "Autodesk Inventor",
            "Prototyping",
            "Manufacturing",
            "Technical Drawings",
            "Design for Manufacturing",
        ],
        responsibilities=[
            "Create and revise mechanical designs",
            "Prototype components and evaluate fit and function",
            "Prepare designs for manufacturing and assembly",
        ],
        interests=["Mechanical design", "Hardware", "Manufacturing", "Building"],
        industries=["Engineering", "Manufacturing", "Technology", "Automotive"],
        education=[
            "Mechanical Engineering",
            "Computer Engineering",
            "Industrial Design",
        ],
        projects=["CAD assembly", "Chassis design", "Manufactured prototype"],
        work_styles=["Hands-on", "Visual", "Iterative"],
        adjacent=[
            "robotics-engineer",
            "manufacturing-engineer",
            "hardware-test-engineer",
        ],
        description="Turns requirements into manufacturable mechanical components, assemblies, prototypes, and technical drawings.",
    ),
    role(
        "manufacturing-engineer",
        "Manufacturing Engineer",
        "Manufacturing Engineering",
        level=2,
        skills=[
            "Manufacturing",
            "Process Improvement",
            "CAD",
            "Quality",
            "Data Analysis",
            "Documentation",
            "Design for Manufacturing",
        ],
        responsibilities=[
            "Design and improve production processes",
            "Analyze quality, throughput, and manufacturing constraints",
            "Coordinate design changes with production teams",
        ],
        interests=["Manufacturing", "Operations", "Engineering", "Efficiency"],
        industries=["Manufacturing", "Engineering", "Automotive", "Technology"],
        education=[
            "Manufacturing Engineering",
            "Mechanical Engineering",
            "Industrial Engineering",
            "Computer Engineering",
        ],
        projects=["Manufacturing plan", "Process improvement", "Quality study"],
        work_styles=["Hands-on", "Structured", "Cross-functional"],
        adjacent=[
            "mechanical-design-engineer",
            "hardware-test-engineer",
            "operations-analyst",
        ],
        description="Improves how physical products are manufactured by connecting design, process, quality, and production data.",
    ),
    role(
        "hardware-test-engineer",
        "Hardware Test Engineer",
        "Hardware Quality and Validation",
        level=1,
        skills=[
            "Hardware Testing",
            "Electronics",
            "Debugging",
            "Test Planning",
            "Data Analysis",
            "Documentation",
            "Soldering",
        ],
        responsibilities=[
            "Design repeatable hardware tests",
            "Diagnose failures and document root causes",
            "Communicate validation results to design teams",
        ],
        interests=["Hardware", "Testing", "Electronics", "Problem solving"],
        industries=["Engineering", "Manufacturing", "Technology", "Healthcare"],
        education=[
            "Computer Engineering",
            "Electrical Engineering",
            "Mechanical Engineering",
        ],
        projects=["Hardware test fixture", "Validation plan", "Failure analysis"],
        work_styles=["Hands-on", "Structured", "Detail oriented"],
        adjacent=[
            "robotics-engineer",
            "embedded-systems-engineer",
            "mechanical-design-engineer",
            "quality-assurance-analyst",
        ],
        description="Builds test methods and evidence that physical systems work reliably and meet design requirements.",
    ),
    role(
        "financial-analyst",
        "Financial Analyst",
        "Finance and Analytics",
        level=2,
        skills=["Financial Analysis", "Excel", "Forecasting", "Data Analysis", "Presentation"],
        responsibilities=[
            "Analyze financial performance",
            "Build forecasts and scenarios",
            "Present risks and recommendations",
        ],
        interests=["Finance", "Business", "Analysis"],
        industries=["Finance", "Technology", "Healthcare", "Retail"],
        education=["Finance", "Economics", "Accounting", "Mathematics"],
        projects=["Financial model", "Budget analysis", "Investment research"],
        work_styles=["Analytical", "Detail oriented", "Deadline driven"],
        adjacent=["data-analyst", "business-analyst", "operations-analyst"],
        pit_titles=["Financial Analyst"],
        description="Evaluates financial performance and builds forecasts to support business decisions.",
    ),
    role(
        "business-analyst",
        "Business Analyst",
        "Business Analysis",
        level=2,
        skills=[
            "Requirements Analysis",
            "Process Mapping",
            "Data Analysis",
            "Communication",
            "Documentation",
        ],
        responsibilities=[
            "Clarify business problems and requirements",
            "Map processes and identify improvements",
            "Coordinate evidence across stakeholders",
        ],
        interests=["Business", "Systems", "Problem solving"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Business", "Economics", "Information Systems"],
        projects=["Process map", "Requirements document", "Business case"],
        work_styles=["Collaborative", "Structured", "Stakeholder facing"],
        adjacent=["product-operations-specialist", "data-analyst", "project-coordinator"],
        description="Connects business needs, data, and process evidence to practical changes.",
    ),
    role(
        "operations-analyst",
        "Operations Analyst",
        "Operations",
        level=2,
        skills=["Process Improvement", "Data Analysis", "Spreadsheets", "Coordination", "Documentation"],
        responsibilities=[
            "Measure operational performance",
            "Improve recurring processes",
            "Coordinate changes across teams",
        ],
        interests=["Operations", "Efficiency", "Business"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Business", "Economics", "Industrial Engineering"],
        projects=["Process improvement", "Operations dashboard", "Workflow redesign"],
        work_styles=["Structured", "Collaborative", "Execution focused"],
        adjacent=["business-analyst", "product-operations-specialist", "project-coordinator"],
        description="Uses data and process analysis to make recurring business operations more effective.",
    ),
    role(
        "product-manager",
        "Product Manager",
        "Product",
        level=3,
        skills=[
            "Product Strategy",
            "User Research",
            "Prioritization",
            "Product Metrics",
            "Communication",
            "Technical fluency",
        ],
        responsibilities=[
            "Research user and customer problems",
            "Prioritize opportunities and tradeoffs",
            "Coordinate delivery and evaluate outcomes",
        ],
        interests=["Product", "Users", "Technology", "Strategy"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Business", "Computer Science", "Design"],
        projects=["Product discovery", "Feature launch", "Roadmap"],
        work_styles=["Cross-functional", "Ambiguous", "Communication intensive"],
        adjacent=["product-operations-specialist", "business-analyst", "software-engineer"],
        pit_titles=["Product Manager"],
        description="Connects user needs, business goals, and technical constraints to guide product decisions.",
    ),
    role(
        "product-operations-specialist",
        "Product Operations Specialist",
        "Product Operations",
        level=2,
        skills=[
            "Project Coordination",
            "Process Design",
            "Product Metrics",
            "Documentation",
            "Communication",
        ],
        responsibilities=[
            "Coordinate product planning processes",
            "Improve product team workflows",
            "Track metrics, decisions, and launch readiness",
        ],
        interests=["Product", "Operations", "Technology"],
        industries=["Technology", "Finance", "Healthcare"],
        education=["Business", "Information Systems", "Communications"],
        projects=["Launch process", "Metrics dashboard", "Workflow redesign"],
        work_styles=["Cross-functional", "Organized", "Execution focused"],
        adjacent=["product-manager", "operations-analyst", "project-coordinator"],
        description="Improves how product teams plan, communicate, measure, and deliver work.",
    ),
    role(
        "project-coordinator",
        "Project Coordinator",
        "Project Management",
        level=1,
        skills=["Project Planning", "Coordination", "Communication", "Documentation", "Scheduling"],
        responsibilities=[
            "Track project milestones and dependencies",
            "Coordinate meetings and follow-up",
            "Maintain project documentation",
        ],
        interests=["Projects", "Organization", "Teamwork"],
        industries=["Technology", "Finance", "Healthcare", "Retail", "Education"],
        education=["Business", "Communications", "Any degree"],
        projects=["Project plan", "Event coordination", "Launch checklist"],
        work_styles=["Organized", "Collaborative", "Deadline driven"],
        adjacent=["product-operations-specialist", "business-analyst", "hr-coordinator"],
        description="Keeps projects organized by coordinating schedules, decisions, dependencies, and communication.",
    ),
    role(
        "ux-designer",
        "UX Designer",
        "Design",
        level=2,
        skills=[
            "User Research",
            "Interaction Design",
            "Prototyping",
            "Usability Testing",
            "Visual Communication",
        ],
        responsibilities=[
            "Research user needs",
            "Design and test interaction flows",
            "Partner with product and engineering",
        ],
        interests=["Design", "Users", "Technology", "Psychology"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Design", "Psychology", "Human Computer Interaction"],
        projects=["UX case study", "Prototype", "Usability study"],
        work_styles=["Creative", "Collaborative", "Iterative"],
        adjacent=["product-manager", "content-strategist", "learning-experience-designer"],
        pit_titles=["UX Designer"],
        description="Researches user needs and designs understandable, useful digital experiences.",
    ),
    role(
        "learning-experience-designer",
        "Learning Experience Designer",
        "Education and Enablement",
        level=2,
        skills=[
            "Instructional Design",
            "Curriculum Development",
            "User Research",
            "Content Creation",
            "Facilitation",
        ],
        responsibilities=[
            "Research learner needs",
            "Design courses and learning activities",
            "Evaluate whether learning experiences work",
        ],
        interests=["Education", "Design", "Psychology", "Communication"],
        industries=["Education", "Technology", "Healthcare"],
        education=["Education", "Psychology", "Design", "Communications"],
        projects=["Course design", "Training program", "Learning evaluation"],
        work_styles=["Creative", "Research oriented", "Collaborative"],
        adjacent=["ux-designer", "content-strategist", "hr-coordinator"],
        description="Designs useful learning experiences by combining research, content, and instructional methods.",
    ),
    role(
        "marketing-specialist",
        "Marketing Specialist",
        "Marketing",
        level=2,
        skills=["Marketing Strategy", "Content Creation", "SEO", "Analytics", "Communication"],
        responsibilities=[
            "Plan and execute marketing campaigns",
            "Create content for target audiences",
            "Analyze campaign performance",
        ],
        interests=["Marketing", "Audience growth", "Content", "Business"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Marketing", "Business", "Communications"],
        projects=["Marketing campaign", "Content calendar", "Audience analysis"],
        work_styles=["Creative", "Deadline driven", "Collaborative"],
        adjacent=["content-strategist", "sales-representative", "product-operations-specialist"],
        pit_titles=["Marketing Specialist"],
        description="Builds campaigns and content to reach audiences and support measurable business goals.",
    ),
    role(
        "content-strategist",
        "Content Strategist",
        "Content and Communications",
        level=2,
        skills=["Content Strategy", "Writing", "Audience Research", "SEO", "Analytics"],
        responsibilities=[
            "Research audience information needs",
            "Plan and create content systems",
            "Measure content performance",
        ],
        interests=["Writing", "Content", "Users", "Marketing"],
        industries=["Technology", "Healthcare", "Education", "Retail"],
        education=["Communications", "English", "Marketing", "Journalism"],
        projects=["Content portfolio", "Editorial strategy", "SEO audit"],
        work_styles=["Creative", "Independent focus", "Collaborative"],
        adjacent=["marketing-specialist", "ux-designer", "learning-experience-designer"],
        description="Plans useful content based on audience needs, business goals, and performance evidence.",
    ),
    role(
        "sales-representative",
        "Sales Representative",
        "Sales",
        level=2,
        skills=["Sales", "Negotiation", "Communication", "Customer Discovery", "CRM"],
        responsibilities=[
            "Identify and qualify customer needs",
            "Present solutions and handle objections",
            "Maintain a sales pipeline",
        ],
        interests=["Business", "Customers", "Negotiation", "Goals"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Business", "Communications", "Any degree"],
        projects=["Sales presentation", "Customer research", "Pipeline analysis"],
        work_styles=["Social", "Goal oriented", "Fast paced"],
        adjacent=["customer-success-specialist", "marketing-specialist", "product-manager"],
        pit_titles=["Sales Representative"],
        description="Works directly with prospective customers to understand needs and earn business.",
    ),
    role(
        "customer-success-specialist",
        "Customer Success Specialist",
        "Customer Experience",
        level=2,
        skills=["Customer Support", "Communication", "Problem Solving", "Training", "CRM"],
        responsibilities=[
            "Help customers adopt a product",
            "Resolve recurring customer problems",
            "Share customer patterns with product teams",
        ],
        interests=["Customers", "Technology", "Teaching", "Problem solving"],
        industries=["Technology", "Finance", "Healthcare"],
        education=["Business", "Communications", "Education"],
        projects=["Customer onboarding", "Support knowledge base", "Retention analysis"],
        work_styles=["Social", "Collaborative", "Service oriented"],
        adjacent=["customer-service-manager", "sales-representative", "product-operations-specialist"],
        description="Helps customers receive value from a product through onboarding, support, and proactive guidance.",
    ),
    role(
        "customer-service-manager",
        "Customer Service Manager",
        "Customer Experience",
        level=3,
        skills=["Customer Support", "Team Leadership", "Process Improvement", "Communication", "Metrics"],
        responsibilities=[
            "Lead customer support operations",
            "Coach service teams",
            "Improve quality and response processes",
        ],
        interests=["Customers", "Leadership", "Operations"],
        industries=["Technology", "Finance", "Healthcare", "Retail"],
        education=["Business", "Communications", "Any degree"],
        projects=["Service quality program", "Support workflow", "Team training"],
        work_styles=["People leadership", "Operational", "Fast paced"],
        adjacent=["customer-success-specialist", "operations-analyst", "hr-coordinator"],
        pit_titles=["Customer Service Manager"],
        description="Leads customer service teams and improves the systems used to resolve customer needs.",
    ),
    role(
        "hr-coordinator",
        "HR Coordinator",
        "People Operations",
        level=1,
        skills=["HR Operations", "Coordination", "Communication", "Documentation", "Recruiting"],
        responsibilities=[
            "Coordinate recruiting and employee processes",
            "Maintain people records and documentation",
            "Support employee questions and programs",
        ],
        interests=["People", "Organization", "Workplace"],
        industries=["Technology", "Finance", "Healthcare", "Retail", "Education"],
        education=["Human Resources", "Business", "Psychology", "Communications"],
        projects=["Recruiting process", "Employee onboarding", "People program"],
        work_styles=["Organized", "People oriented", "Confidential"],
        adjacent=["project-coordinator", "learning-experience-designer", "customer-success-specialist"],
        pit_titles=["HR Coordinator"],
        description="Coordinates recruiting, onboarding, records, and employee programs.",
    ),
    role(
        "engineering-manager",
        "Engineering Manager",
        "Software Engineering",
        level=4,
        skills=[
            "Software Engineering",
            "People Leadership",
            "Technical Strategy",
            "Planning",
            "Communication",
        ],
        responsibilities=[
            "Lead and coach software engineers",
            "Set technical direction and delivery expectations",
            "Coordinate staffing, quality, and stakeholder decisions",
        ],
        interests=["Technology", "Leadership", "Teams", "Strategy"],
        industries=["Technology", "Finance", "Healthcare"],
        education=["Computer Science", "Software Engineering"],
        projects=["Technical roadmap", "Team leadership", "Architecture program"],
        work_styles=["People leadership", "Strategic", "Cross-functional"],
        adjacent=["software-engineer", "product-manager", "devops-engineer"],
        description="Leads software teams and combines people management with technical and delivery judgment.",
    ),
]


ROLE_BY_ID = {item["id"]: item for item in OCCUPATIONAL_TAXONOMY}

TITLE_ALIASES = {
    "developer": "software-engineer",
    "software developer": "software-engineer",
    "web developer": "software-engineer",
    "frontend engineer": "software-engineer",
    "backend engineer": "software-engineer",
    "site reliability engineer": "devops-engineer",
    "sre": "devops-engineer",
    "machine learning engineer": "data-scientist",
    "ml engineer": "data-scientist",
    "business intelligence analyst": "data-analyst",
    "bi analyst": "data-analyst",
    "product designer": "ux-designer",
    "interaction designer": "ux-designer",
    "associate product manager": "product-manager",
    "technical product manager": "product-manager",
    "product ops": "product-operations-specialist",
    "project manager": "project-coordinator",
    "program coordinator": "project-coordinator",
    "account executive": "sales-representative",
    "customer success manager": "customer-success-specialist",
    "support specialist": "customer-success-specialist",
    "recruiting coordinator": "hr-coordinator",
    "people operations coordinator": "hr-coordinator",
    "instructional designer": "learning-experience-designer",
    "test engineer": "quality-assurance-analyst",
    "qa engineer": "quality-assurance-analyst",
    "security analyst": "cybersecurity-analyst",
    "robotics engineer": "robotics-engineer",
    "robotics member": "robotics-engineer",
    "robotics 101 member": "robotics-engineer",
    "robotics team member": "robotics-engineer",
    "mechatronics engineer": "robotics-engineer",
    "embedded engineer": "embedded-systems-engineer",
    "firmware engineer": "embedded-systems-engineer",
    "embedded systems engineer": "embedded-systems-engineer",
    "mechanical design engineer": "mechanical-design-engineer",
    "chassis engineer": "mechanical-design-engineer",
    "mechanical engineer": "mechanical-design-engineer",
    "cad engineer": "mechanical-design-engineer",
    "manufacturing engineer": "manufacturing-engineer",
    "process engineer": "manufacturing-engineer",
    "hardware test engineer": "hardware-test-engineer",
    "validation engineer": "hardware-test-engineer",
    "test and validation engineer": "hardware-test-engineer",
    "data analytics": "data-analyst",
    "data and analytics": "data-analyst",
    "data & analytics": "data-analyst",
    "analytics intern": "data-analyst",
}

for item in OCCUPATIONAL_TAXONOMY:
    TITLE_ALIASES[item["title"].lower()] = item["id"]
    for pit_title in item["pitTitles"]:
        TITLE_ALIASES[pit_title.lower()] = item["id"]


CONCEPT_ALIASES: dict[str, list[str]] = {
    "programming": [
        "programming",
        "coding",
        "software development",
        "developer",
        "algorithm",
        "algorithms",
    ],
    "python": ["python", "pandas", "numpy"],
    "javascript": ["javascript", "typescript", "react", "next.js", "node.js"],
    "apis": ["api", "apis", "rest", "graphql", "backend"],
    "debugging": ["debugging", "troubleshooting", "root cause"],
    "testing": ["testing", "quality assurance", "qa", "test automation"],
    "cloud": ["cloud", "aws", "azure", "gcp"],
    "automation": ["automation", "automated", "scripting", "ci/cd"],
    "security": ["cybersecurity", "information security", "network security", "threat"],
    "data analysis": ["data analysis", "analytics", "analyzed data", "dashboard", "sql"],
    "statistics": ["statistics", "statistical", "regression", "probability"],
    "machine learning": ["machine learning", "ml", "predictive model", "ai model"],
    "visualization": ["visualization", "tableau", "power bi", "dashboard"],
    "finance": ["finance", "financial", "forecast", "budget", "accounting"],
    "requirements": ["requirements", "business analysis", "process mapping"],
    "process improvement": ["process improvement", "workflow", "operations", "efficiency"],
    "product": ["product management", "product strategy", "roadmap", "feature planning"],
    "user research": ["user research", "customer discovery", "interviews", "usability"],
    "prioritization": ["prioritization", "prioritize", "tradeoffs", "roadmap"],
    "project coordination": ["project coordination", "project management", "scheduling", "milestones"],
    "design": ["ux", "ui", "interaction design", "product design", "figma"],
    "prototyping": ["prototype", "prototyping", "wireframe", "mockup"],
    "marketing": ["marketing", "campaign", "seo", "audience growth"],
    "content": ["content", "writing", "editorial", "copywriting"],
    "sales": ["sales", "pipeline", "prospecting", "negotiation"],
    "customer support": ["customer support", "customer service", "help desk", "client support"],
    "customer success": ["customer success", "onboarding customers", "retention"],
    "human resources": ["human resources", "hr", "recruiting", "people operations"],
    "education": ["education", "teaching", "instruction", "curriculum", "training"],
    "leadership": ["leadership", "managed", "manager", "led a team", "mentored"],
    "communication": ["communication", "presentation", "public speaking", "stakeholder"],
    "documentation": ["documentation", "documented", "technical writing", "requirements document"],
    "research": ["research", "study", "experiment", "investigation"],
    "psychology": ["psychology", "behavioral", "human behavior"],
    "robotics": ["robotics", "robot", "battlebots", "autonomous system"],
    "cad": ["cad", "autodesk inventor", "autodesk fusion", "fusion 360"],
    "mechanical design": [
        "mechanical design",
        "chassis",
        "mechanical training",
        "technical drawing",
    ],
    "embedded systems": [
        "embedded systems",
        "embedded system",
        "arduino",
        "microcontroller",
        "firmware",
    ],
    "electronics": ["electronics", "soldering", "circuit", "sensor"],
    "manufacturing": [
        "manufacturing",
        "makerspace",
        "3d printing",
        "3d printer",
        "design for manufacturing",
    ],
    "hardware testing": [
        "hardware testing",
        "hardware test",
        "validation plan",
        "test fixture",
        "failure analysis",
    ],
    "logical reasoning": [
        "logic",
        "logical reasoning",
        "mathematical reasoning",
        "algorithmic thinking",
        "proof",
        "proofs",
    ],
    "problem solving": [
        "problem solving",
        "problem-solving",
        "systems thinking",
        "root cause",
        "troubleshooting",
        "debugging",
        "testing",
    ],
    "creative practice": [
        "creative",
        "creative coding",
        "art",
        "music",
        "film",
        "animation",
        "interactive media",
        "visual storytelling",
    ],
}


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "item"


def contains_alias(text: str, alias: str) -> bool:
    normalized_text = re.sub(r"[^a-z0-9+#]+", " ", text.lower()).strip()
    normalized_alias = re.sub(r"[^a-z0-9+#]+", " ", alias.lower()).strip()
    if not normalized_text or not normalized_alias:
        return False
    return f" {normalized_alias} " in f" {normalized_text} "


def normalize_title(value: str) -> str | None:
    text = re.sub(r"\s+", " ", value.lower()).strip()
    text = re.sub(
        r"\b(intern|internship|junior|jr\.?|mid-level|mid level|senior|sr\.?|lead|principal)\b",
        "",
        text,
    )
    text = re.sub(r"\s+", " ", text).strip(" ,-")
    if text in TITLE_ALIASES:
        return TITLE_ALIASES[text]
    for alias, role_id in sorted(
        TITLE_ALIASES.items(), key=lambda item: len(item[0]), reverse=True
    ):
        if alias in text:
            return role_id
    return None


def semantic_concepts(values: list[str]) -> set[str]:
    combined = " ".join(values).lower()
    concepts: set[str] = set()
    for concept, aliases in CONCEPT_ALIASES.items():
        if any(contains_alias(combined, alias) for alias in aliases):
            concepts.add(concept)
    return concepts


def role_concepts(item: dict[str, Any]) -> set[str]:
    return semantic_concepts(
        [
            item["title"],
            item["description"],
            *item["skills"],
            *item["responsibilities"],
            *item["interests"],
            *item["industries"],
            *item["education"],
            *item["projects"],
            *item["workStyles"],
        ]
    )
